# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9e5661c698c82e3aaa0e4cbb524279b7"
name = "dev-edition-turbo-funcs"
handle = "dev-edition-turbo-funcs"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "dev-editions-checkout-201.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
